# Example configuration for discord-stt bot
# Copy this file to bot.toml and edit values as needed

# Discord bot configuration
[discord]
# List of (numeric) user IDs allowed to use commands
allowed_commanders = []

# Whisper model configuration
[whisper]
# Model name for speech-to-text
model = "openai/whisper-small.en"
# Log probability threshold for Whisper transcription (lower = more speculative)
logprob_threshold = -1.0
# No speech threshold for Whisper (0.0-1.0, lower = more strict about detecting speech)
no_speech_threshold = 0.1
# Initial prompt for Whisper to condition the transcription. You can add a few proper nouns here as hints.
prompt = "Dungeons and Dragons, spell, roll, saving throw, initiative, owlbear, dndbeyond, discord."

# Voice handling configuration
[voice]
# Seconds of silence before ending a segment
silence_threshold_seconds = 1.25
# Voice Activity Detection (VAD) threshold for Silero VAD (0.0-1.0, higher = more strict)
vad_threshold = 0.75
# Maximum allowed speech buffer length in seconds before forced into processing (0 = disabled)
max_speech_buf_seconds = 60

# Configuration for generating outlines.
[wrapup]
# OpenAI model name
model = "gpt-4o-mini"
# List of tips for the wrapup LLM.
tips = []

# Mapping of usernames to aliases.
[username_map]

# Mapping of phrases to remap in the chat log.
[phrase_map]

# Configuration for the transcript refiner using Ollama
[refiner]
# The name of the Ollama model to use for refining transcripts.
# Leave this blank to disable the refiner
model = "hf.co/google/gemma-3-4b-it-qat-q4_0-gguf:Q4_0"
# The number of previous log entries to provide as context to the refiner model
context_log_lines = 10
# The temperature for the refiner model (0.0-1.0, lower = more deterministic)
temperature = 0.5
# Timeout in seconds for refiner operations
timeout = 5.0
# The system prompt for the refiner model (transcription editor instructions)
prompt = """You will be given a new line of dialogue from an ongoing voice chat of a Dungeons and Dragons game.
It will sometimes contain some misinterpretations and artifacts.
Your task is to identify and correct those mistakes and only those mistakes.
Ultimately we want a faithful transcript, so preserve as much of the original content as possible.
All content is relevant to the narrative unless obviously a transcription artifact.
Preserve the tone, style, and speaker intent.
Retain any offensive language.
Never omit rolls or other game mechanics.
You will also be given past (vetted) dialogue for context only.

Transcription artifacts come from background noise, make no contextual sense, and usually appear as:
- Unsolicited "I don't know"
- Unsolicited "Bye"
- Unsolicited "Sorry"
- Unsolicited "Thank you"
- Phrases or words repeated several (3+) times.
If the entire transcription seems to be a transcription artifact, return nothing for the content.
When in doubt, keep the original transcription."""