# Example configuration for discord-stt bot
# Copy this file to bot.toml and edit values as needed

# Discord bot configuration
[discord]
# List of (numeric) user IDs allowed to use commands
allowed_commanders = []

# Mapping of usernames to character names
[username_map]

# Whisper model configuration
[whisper]
# Model name for speech-to-text
model = "openai/whisper-small.en"
# Log probability threshold for Whisper transcription (lower = more speculative)
logprob_threshold = -1.0

# Voice handling configuration
[voice]
# Seconds of silence before ending a segment
silence_threshold_seconds = 1.25
# Voice Activity Detection (VAD) threshold for Silero VAD (0.0-1.0, higher = more strict)
vad_threshold = 0.66
# Maximum allowed speech buffer size in bytes before forced processing (0 = disabled)
max_speech_buf_bytes = 2097152  # 2MB default, adjust as needed

# Configuration for generating outlines.
[llm]
# OpenAI model name
model = "gpt-4o-mini"
# List of proper nouns to attempt to recognize
proper_nouns = []
# List of tips for the wrapup LLM.
tips = []
